### ISSUE TITLE
Block comment for example program

### ISSUE THREAD

**Issue by FRex** [lifthrasiir/j40#7]
If a block comment `/* */` was used instead of many one line `//` comments around the example program, then it could be copy pasted easier, with no need to remove all the `//` by hand or using an editor (many don't offer multi-line comment/uncomment).

**Comment by lifthrasiir** [comment]
Good point, does acfe38647a0614e0562f739d4a40d2fc8a397e7f look fine to you?

**Comment by FRex** [comment]
Yes, that's the change I meant. I'm glad you like the idea.
